name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository to access your files

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}  # Use Node.js versions from the matrix

    - name: Install dependencies
      run: |
        npm install
        npm rebuild bcrypt --build-from-source  # Rebuild bcrypt

    - name: Run tests
      run: npm test

    - name: Debug - List files in the current directory  # Optional debugging
      run: ls -alh
